spring:
  profiles:
    active: ${ENV:dev}

taokouling:
  appkey: MXDTGTjRNW
  api: https://api.taokouling.com/tkl/tkljm

tran-server:
  port: 13570

ffmpeg:
  path: ${FFMPEG_PATH}
  tmp-dir: ${FFMPEG_TMP_DIR}

asr:
  host: ${ASR_HOST}
  port: ${ASR_PORT}
  username: ${ASR_USERNAME}
  password: ${ASR_PASSWORD}
