

FFMPEG_PATH: "D:\ffmpeg"
FFMPEG_TMP_DIR: "D:\ffmpeg\tmp"

#ASR_HOST: 172.18.36.228
#ASR_PORT: 9091
#ASR_USERNAME: aiyin_zhijian
#ASR_PASSWORD: aiyin_zhijian123456#

#ASR_HOST: 120.77.147.194
#ASR_PORT: 9091
#ASR_USERNAME: aiyin_zhijian
#ASR_PASSWORD: aiyin_zhijian123456#

ASR_HOST: 172.18.26.142
ASR_PORT: 9092
ASR_USERNAME: aiyin_zhijian
ASR_PASSWORD: aiyin_zhijian123456#

#ASR_HOST: 39.108.172.246
#ASR_PORT: 9092
#ASR_USERNAME: aiyin_zhijian
#ASR_PASSWORD: aiyin_zhijian123456#